name: among_tani
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sqflite: ^0.11.0+1
  path_provider: ^0.4.0

  webview_flutter: ^0.3.19+7
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+5
  toast: ^0.1.5
  retrofit: ^1.3.0
  logger: ^0.8.3
  json_serializable: ^3.2.1
  dio: 3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.3.0
  build_runner: ^1.7.4
flutter:
  uses-material-design: true

  assets:
  - assets/logo.png
  - assets/batu7.JPG

fonts:
  - family: Nunito
    fonts:
      - asset: assets/Nunito.ttf
